# Generated by Django 5.0.1 on 2026-05-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Lista de features/equipamentos do veículo (ex: ar condicionado, direção hidráulica, etc.)'),
        ),
    ]
